deploy:
  image: node:latest
  stage: deploy
  only:
    - master
  script:
    - npm install -g firebase-tools
    - npm install
    - npm rebuild node-sass
    - npm run build:prod
    - firebase deploy --token $FIREBASE_DEPLOY_KEY
  cache:
    paths:
      - node_modules/
